#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlidingFragments.Resource", IsApplication=true)]

namespace SlidingFragments
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_fragment_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_fragment_out = 2130968577;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int white = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int slide_fragment_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int slide_up_down_fraction = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int text_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int text_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int golden_gate = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0002
			public const int dark_hover_view = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int move_fragment = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int move_to_back_container = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int half_slide_up_down_duration = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int slide_up_down_duration = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int slide_up_down_final_value = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int image_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sliding_fragments_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int text_fragment = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int address = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int bridge = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int construction = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int elevation = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int height = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int length = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int photo_credits = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int span = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int summary = 2131230727;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
